import { useState } from 'react';
import { X, Printer, Mail, Plane, Hotel, Star, Calendar, Bookmark, ChevronDown, Pencil, Check, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { useTripStore } from '@/store/tripStore';
import { format } from 'date-fns';
import { cn } from '@/lib/utils';

const TIME_SLOTS = ['Morning', 'Afternoon', 'Evening', 'Unscheduled'];
const SLOT_ICONS = { Morning: '🌅', Afternoon: '☀️', Evening: '🌙', Unscheduled: '📌' };

function buildEmailBody(days, savedActivities, savedEvents, activityTimeSlots, activityNotes, trip) {
  let body = `TripForge Itinerary\n`;
  body += `${trip?.originCity || ''} Trip\n`;
  if (trip?.departureDate && trip?.returnDate) {
    body += `${trip.departureDate} – ${trip.returnDate}\n`;
  }
  body += `\n`;

  days.forEach((day, i) => {
    body += `─────────────────────────\n`;
    body += `Day ${day.dayNumber} — ${day.label}\n`;
    if (day.location) body += `📍 ${day.location}\n`;
    body += `\n`;

    const activities = savedActivities[i] || [];
    const events = savedEvents[i] || [];

    if (activities.length > 0) {
      body += `Activities:\n`;
      TIME_SLOTS.forEach((slot) => {
        const slotActivities = activities.filter((a) => {
          const key = `${i}-${a.name}`;
          const assigned = activityTimeSlots[key] || 'Unscheduled';
          return assigned === slot;
        });
        if (slotActivities.length === 0) return;
        body += `  ${SLOT_ICONS[slot]} ${slot}:\n`;
        slotActivities.forEach((a) => {
          body += `    • ${a.name} (${a.duration || ''} · ${a.price_range || ''})\n`;
          const note = activityNotes[`${i}-${a.name}`];
          if (note) body += `      Note: ${note}\n`;
        });
      });
    }

    if (events.length > 0) {
      body += `Events:\n`;
      events.forEach((e) => {
        body += `  🎟️ ${e.title}\n`;
        if (e.url) body += `     ${e.url}\n`;
      });
    }

    body += `\n`;
  });

  body += `\nGenerated by TripForge`;
  return body;
}

function ActivityItem({ activity, dayIndex }) {
  const { removeActivity, setActivityTimeSlot, setActivityNote, activityTimeSlots, activityNotes } = useTripStore();
  const key = `${dayIndex}-${activity.name}`;
  const slot = activityTimeSlots[key] || 'Unscheduled';
  const note = activityNotes[key] || '';
  const [editingNote, setEditingNote] = useState(false);
  const [noteValue, setNoteValue] = useState(note);

  const handleSaveNote = () => {
    setActivityNote(dayIndex, activity.name, noteValue);
    setEditingNote(false);
  };

  return (
    <div className="group py-2">
      <div className="flex items-start gap-2">
        <Star className="h-3.5 w-3.5 text-forge-500 mt-0.5 flex-shrink-0" />
        <div className="flex-1 min-w-0">
          <div className="flex items-start justify-between gap-1">
            <span className="font-medium text-xs leading-tight">{activity.name}</span>
            <Button
              variant="ghost"
              size="icon"
              className="h-5 w-5 opacity-0 group-hover:opacity-100 flex-shrink-0 -mr-1"
              onClick={() => removeActivity(dayIndex, activity.name)}
              title="Remove"
            >
              <Trash2 className="h-3 w-3 text-destructive" />
            </Button>
          </div>
          <div className="flex items-center gap-2 mt-1 flex-wrap">
            <span className="text-xs text-muted-foreground">
              {activity.duration} · {activity.price_range}
            </span>
          </div>

          {/* Time slot selector */}
          <div className="flex items-center gap-1.5 mt-1.5">
            <span className="text-xs">{SLOT_ICONS[slot]}</span>
            <Select
              value={slot}
              onValueChange={(v) => setActivityTimeSlot(dayIndex, activity.name, v)}
            >
              <SelectTrigger className="h-5 text-xs border-dashed w-auto min-w-0 px-1.5 gap-0.5 [&>svg]:h-3 [&>svg]:w-3">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {TIME_SLOTS.map((s) => (
                  <SelectItem key={s} value={s} className="text-xs">
                    {SLOT_ICONS[s]} {s}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Note */}
          {editingNote ? (
            <div className="mt-1.5 space-y-1">
              <Textarea
                value={noteValue}
                onChange={(e) => setNoteValue(e.target.value)}
                placeholder="Add a note…"
                className="text-xs min-h-[50px] resize-none"
                autoFocus
              />
              <div className="flex gap-1">
                <Button size="sm" variant="outline" className="h-5 text-xs px-2 gap-0.5" onClick={handleSaveNote}>
                  <Check className="h-3 w-3" /> Save
                </Button>
                <Button size="sm" variant="ghost" className="h-5 text-xs px-2" onClick={() => { setEditingNote(false); setNoteValue(note); }}>
                  Cancel
                </Button>
              </div>
            </div>
          ) : (
            <div className="mt-1">
              {note ? (
                <button
                  className="text-xs text-muted-foreground italic hover:text-foreground flex items-center gap-1 group/note"
                  onClick={() => { setNoteValue(note); setEditingNote(true); }}
                >
                  <Pencil className="h-2.5 w-2.5 opacity-0 group-hover/note:opacity-100 transition-opacity" />
                  {note}
                </button>
              ) : (
                <button
                  className="text-xs text-muted-foreground hover:text-forge-500 transition-colors flex items-center gap-1"
                  onClick={() => setEditingNote(true)}
                >
                  <Pencil className="h-2.5 w-2.5" />
                  Add note
                </button>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function EventItem({ event, dayIndex }) {
  const { removeEvent } = useTripStore();
  return (
    <div className="group flex items-start gap-2 py-1.5 text-xs">
      <Bookmark className="h-3.5 w-3.5 text-purple-500 mt-0.5 flex-shrink-0" />
      <div className="flex-1 min-w-0">
        <span className="font-medium">{event.title}</span>
        {event.url && (
          <a href={event.url} target="_blank" rel="noopener noreferrer" className="block text-muted-foreground hover:text-forge-500 truncate mt-0.5">
            {event.url.replace(/^https?:\/\/(www\.)?/, '').slice(0, 40)}…
          </a>
        )}
      </div>
      <Button
        variant="ghost"
        size="icon"
        className="h-5 w-5 opacity-0 group-hover:opacity-100 flex-shrink-0"
        onClick={() => removeEvent(dayIndex, event.title)}
        title="Remove"
      >
        <Trash2 className="h-3 w-3 text-destructive" />
      </Button>
    </div>
  );
}

export function PackPanel() {
  const {
    currentTrip, savedActivities, savedEvents, activityTimeSlots, activityNotes, togglePackPanel,
  } = useTripStore();
  const days = currentTrip?.days || [];

  const handlePrint = () => {
    window.print();
  };

  const handleEmail = () => {
    if (!currentTrip) return;
    const subject = `My TripForge Itinerary — ${currentTrip.originCity || 'Trip'}`;
    const body = buildEmailBody(days, savedActivities, savedEvents, activityTimeSlots, activityNotes, currentTrip);
    window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };

  const totalActivities = Object.values(savedActivities).reduce((acc, arr) => acc + arr.length, 0);
  const totalEvents = Object.values(savedEvents).reduce((acc, arr) => acc + arr.length, 0);

  return (
    <>
      {/* Print-only styles */}
      <style>{`
        @media print {
          body > *:not(.pack-panel-print) { display: none !important; }
          .pack-panel-print { display: block !important; position: static !important; width: 100% !important; height: auto !important; overflow: visible !important; }
          .no-print { display: none !important; }
        }
      `}</style>

      <div className="h-full flex flex-col pack-panel-print">
        <div className="flex items-center justify-between p-4 border-b no-print">
          <div>
            <h2 className="font-semibold flex items-center gap-2">🎒 Pack my bag</h2>
            <p className="text-xs text-muted-foreground">
              {totalActivities} activit{totalActivities === 1 ? 'y' : 'ies'} · {totalEvents} event{totalEvents === 1 ? '' : 's'}
            </p>
          </div>
          <div className="flex gap-1.5">
            <Button size="sm" variant="outline" onClick={handleEmail} className="gap-1 text-xs h-8" title="Email itinerary">
              <Mail className="h-3.5 w-3.5" />
              <span className="hidden sm:inline">Email</span>
            </Button>
            <Button size="sm" variant="outline" onClick={handlePrint} className="gap-1 text-xs h-8" title="Print / Save as PDF">
              <Printer className="h-3.5 w-3.5" />
              <span className="hidden sm:inline">Print</span>
            </Button>
            <Button size="icon" variant="ghost" className="h-8 w-8" onClick={togglePackPanel}>
              <X className="h-4 w-4" />
            </Button>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-4 space-y-5">
          {days.length === 0 ? (
            <p className="text-sm text-muted-foreground text-center py-8">
              No trip data yet. Complete the wizard first!
            </p>
          ) : (
            days.map((day, i) => {
              const flightBooked = (currentTrip?.flightLegs || []).find(
                (leg) => leg.isBooked && leg.date === day.date
              );
              const hotelBooked = (currentTrip?.hotelStays || []).find(
                (stay) => stay.isBooked && stay.checkin <= day.date && stay.checkout >= day.date
              );
              const activities = savedActivities[i] || [];
              const events = savedEvents[i] || [];
              const hasContent = flightBooked || hotelBooked || activities.length > 0 || events.length > 0;

              return (
                <div key={day.date}>
                  {/* Day header */}
                  <div className="flex items-center gap-2 mb-2">
                    <span className="text-xs font-bold text-forge-600 bg-forge-100 dark:bg-forge-950/40 px-2 py-0.5 rounded-full">
                      Day {day.dayNumber}
                    </span>
                    <span className="text-sm font-semibold truncate">{day.location || 'TBD'}</span>
                    <span className="text-xs text-muted-foreground ml-auto flex-shrink-0">{day.label}</span>
                  </div>

                  {/* Flight */}
                  {flightBooked && (
                    <div className="flex items-start gap-2 py-1.5 text-xs">
                      <Plane className="h-3.5 w-3.5 text-blue-500 mt-0.5 flex-shrink-0" />
                      <div>
                        <span className="font-medium">{flightBooked.airline || 'Flight'}</span>
                        {flightBooked.flightNumber && <span className="text-muted-foreground"> {flightBooked.flightNumber}</span>}
                      </div>
                    </div>
                  )}

                  {/* Hotel */}
                  {hotelBooked && (
                    <div className="flex items-start gap-2 py-1.5 text-xs">
                      <Hotel className="h-3.5 w-3.5 text-purple-500 mt-0.5 flex-shrink-0" />
                      <div>
                        <span className="font-medium">{hotelBooked.name || 'Hotel'}</span>
                        {hotelBooked.confirmation && (
                          <span className="text-muted-foreground"> #{hotelBooked.confirmation}</span>
                        )}
                      </div>
                    </div>
                  )}

                  {/* Activities grouped by time slot */}
                  {activities.length > 0 && (
                    <div className="mt-1">
                      {TIME_SLOTS.map((slot) => {
                        const slotActivities = activities.filter((a) => {
                          const assigned = activityTimeSlots[`${i}-${a.name}`] || 'Unscheduled';
                          return assigned === slot;
                        });
                        if (slotActivities.length === 0) return null;
                        return (
                          <div key={slot} className="mb-1">
                            <div className="flex items-center gap-1 text-xs text-muted-foreground font-medium mb-0.5 ml-5">
                              {SLOT_ICONS[slot]} {slot}
                            </div>
                            {slotActivities.map((act) => (
                              <ActivityItem key={act.name} activity={act} dayIndex={i} />
                            ))}
                          </div>
                        );
                      })}
                    </div>
                  )}

                  {/* Saved events */}
                  {events.length > 0 && (
                    <div className="mt-1">
                      <div className="text-xs text-muted-foreground font-medium mb-0.5 ml-5">
                        📅 Events
                      </div>
                      {events.map((ev) => (
                        <EventItem key={ev.title} event={ev} dayIndex={i} />
                      ))}
                    </div>
                  )}

                  {!hasContent && (
                    <p className="text-xs text-muted-foreground italic pl-5">
                      Nothing planned yet — explore the tabs to add activities and events.
                    </p>
                  )}

                  <Separator className="mt-3" />
                </div>
              );
            })
          )}

          {/* Email reminders section */}
          <div className="rounded-lg border border-dashed p-4 space-y-2">
            <div className="flex items-center gap-2">
              <Calendar className="h-4 w-4 text-forge-500" />
              <span className="text-sm font-medium">Email reminders</span>
            </div>
            <p className="text-xs text-muted-foreground">
              Get a daily digest of upcoming events and activities for each day of your trip.
            </p>
            <Button
              size="sm"
              variant="outline"
              className="w-full gap-1.5 text-xs"
              onClick={() => {
                const subject = `Set up TripForge reminders for my trip`;
                const body = `Hi!\n\nI'd like to set up daily event reminders for my trip:\n${currentTrip?.originCity || ''} → ${currentTrip?.days?.[0]?.location || ''}\n${currentTrip?.departureDate || ''} – ${currentTrip?.returnDate || ''}\n\nPlease send me daily event recommendations.`;
                window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
              }}
            >
              <Mail className="h-3.5 w-3.5" />
              Email itinerary to yourself
            </Button>
            <p className="text-xs text-muted-foreground text-center">
              For automated daily reminders, use the "Email" button above to send your full itinerary to yourself, then set a recurring calendar reminder.
            </p>
          </div>
        </div>
      </div>
    </>
  );
}
